# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Self-hosted

steps:
- powershell: |
    Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force
    Invoke-WebRequest -Uri https://github.com/github/codeql-cli-binaries/releases/download/v2.9.2/codeql.zip -OutFile codeql.zip
    Expand-Archive -Path codeql.zip -DestinationPath codeql
    $env:PATH += ";$(pwd)\codeql"
    git clone https://github.com/github/codeql-action.git
    .\codeql-action\init.ps1
    .\codeql\codeql.exe database create codeql-db --language=javascript --source-root=.
    .\codeql\codeql.exe database analyze codeql-db --format=sarif-latest --output=codeql-analysis.sarif
  displayName: 'Run CodeQL Analysis'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)\codeql-analysis.sarif'
    artifactName: 'CodeQLAnalysisResults'
    publishLocation: 'Container'
  displayName: 'Publish CodeQL Analysis Results'
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'