# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Self-hosted

steps:
- task: PowerShell@2
  displayName: 'Checkout codeql-anywhere'
  inputs:
    targetType: inline
    script: |
      if (Test-Path './.git/modules/codeql-anywhere') {rm -rf './.git/modules/codeql-anywhere'}
      git submodule add https://github.com/david-wiggs/codeql-anywhere.git
    pwsh: true

- task: PowerShell@2
  displayName: 'Run New-CodeQLScan.ps1'
  inputs:
    targetType: filePath
    filePath: 'codeql-anywhere/resources/scripts/New-CodeQLScan.ps1'
    pwsh: true
  env:
    # GITHUB_TOKEN environment variable must be set to pass in the secret value defined in the $(GHAS_ADO) ADO pipeline variable
    GITHUB_TOKEN: $(GHAS_ADO)
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'