# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Self-hosted

variables:
  GITHUB_OWNER: 'Eugenetanwl3881'
  GITHUB_REPO: 'js-e2e-express-server'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    git clone https://github.com/github/codeql.git
    codeql database create codeql-db --language=javascript --source-root=$(Build.SourcesDirectory)
    codeql database finalize codeql-db
    codeql database analyze codeql-db --format=sarif-latest --output=$(Build.SourcesDirectory)/codeql-analysis.sarif
  displayName: 'Run CodeQL Analysis'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)\codeql-analysis.sarif'
    artifactName: 'CodeQLAnalysisResults'
    publishLocation: 'Container'
  displayName: 'Publish CodeQL Analysis Results'


- script: |
    curl -H "Authorization: token %GITHUB_TOKEN%" ^
         -H "Accept: application/vnd.github.v3+json" ^
         -H "Content-Type: application/json" ^
         --data @%BUILD_SOURCESDIRECTORY%\codeql-analysis.sarif ^
         https://api.github.com/repos/%GITHUB_OWNER%/%GITHUB_REPO%/code-scanning/sarifs
  displayName: 'Upload CodeQL Results to GitHub'
  
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)